# Generated by Django 3.1.12 on 2025-03-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubmitForm',
        ),
    ]
